version: '3.9'
services:
  angular:
    container_name: virtus_angular
    image: virtus/virtus:1.0.1
    #ports:
    #  - 9000:4200
    volumes:
      - './app:/app'
    command: "ng serve --host 0.0.0.0 --disable-host-check"
    restart: always
    networks:
      - virtus_bridge
  pocketbase:
    container_name: virtus_pocketbase
    image: 'ghcr.io/muchobien/pocketbase:latest'
    restart: unless-stopped
    command:
      - pocketbase
      - serve
      - --http
      - 0.0.0.0:8090
      - --dir
      - /data
      - --encryptionEnv
      - ENCRYPTION
    environment:
      ENCRYPTION: "${ENCRYPTION}"
    #ports:
    #  - "8090:8090"
    volumes:
      - ./pocketbase:/data
    networks:
      - virtus_bridge
  nginx_ssl:
    container_name: virtus_nginx
    #hostname: reverse
    image: nginx
    tty: true
    ports:
      - 9000:443
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/ssl/
      - ./nginx/html/:/var/www/html
      - ./nginx/logs:/etc/nginx/logs
    restart: always
    depends_on:
      - angular
      - pocketbase
    networks:
      - virtus_bridge
networks:
  virtus_bridge:
    driver: bridge
