version: '3'
services:
  angular:
    container_name: virtus_angular
    image: virtus/harmony
    #ports:
    #  - 9000:4200
    volumes:
      - './virtus/app:/app'
    command: "ng serve --host 0.0.0.0 --disable-host-check"
    restart: always
    networks:
      - virtus_bridge
  pocketbase:
    container_name: virtus_pocketbase
    image: 'ghcr.io/acifani/pocketbase:0.2-arm64'
    #ports:
    #  - '8090:8090'
    volumes:
      - './pocketbase/pb_data:/pocketbase/pb_data'
      - './pocketbase/pb_public:/pocketbase/pb_public'
    restart: always
    networks:
      - virtus_bridge
  nginx_ssl:
    container_name: virtus_nginx
    #hostname: reverse
    image: nginx
    tty: true
    ports:
      - 9000:443
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/ssl/
      - ./nginx/html/:/var/www/html
      - ./nginx/logs:/etc/nginx/logs
    restart: always
    depends_on:
      - angular
    networks:
      - virtus_bridge
networks:
  virtus_bridge:
    driver: bridge